### ISSUE TITLE
SEO treatment on schema/post.js

### ISSUE THREAD

**Issue by louisguitton** [sanity-io/nextjs-blog-with-comments#3]
Hi, thanks for this starter.

At the moment, the post schema contains only the data required to display the post, but I couldn't find the metadata required for SEO.
For example:
- description
- canonical URL
- open graph meta tags
- JSON-LD structure data (for example https://developers.google.com/search/docs/advanced/structured-data/article)

How are sanity users proceeding? and in particular, how are users of this starter applying SEO treatment to their posts? 

cc:  @kmelve @brob @kapehe-ok

**Comment by louisguitton** [comment]
I've found this in Hull https://github.com/ndimatteo/HULL/blob/main/studio/schemas/documents/settings-seo.js

**Comment by kmelve** [comment]
Hi! This is a fairly minimal example, so there is a lot that it doesn't do right out of the box.

My advice would be to follow [the official Next.js docs and their directions on SEO](https://nextjs.org/learn/seo/introduction-to-seo). For the data part, you can choose if you want to derive the data from common fields, or add SEO-specific fields/overrides.
